name: asthma_app
description: "Eine Asthma-Management App."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  fitbitter: ^2.0.6
  logger: ^2.5.0
  flutter:
    sdk: flutter
  uuid: ^4.0.0
  intl: ^0.20.2

  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1

  shared_preferences: ^2.2.2

  fl_chart: ^1.1.1
  http: ^1.5.0
  geolocator: ^14.0.2
  permission_handler: ^11.3.1
  flutter_local_notifications: ^18.0.1

  url_launcher: ^6.2.6
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
